bazel run --jobs=2 //resources/grammar:publish-samples
gcloud auth application-default login
gcloud auth application-default set-quota-project jomof-sandbox
bazel run --jobs=2 //resources/grammar:publish-samples
cd resources/original/bunpro/
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
rm -rf sample
./sample.sh 
rm -rf sample
./sample.sh 
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run --jobs=2 //resources/grammar:publish-samples --verbose
bazel run --jobs=2 //resources/grammar:publish-samples --subcommands
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')

(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/たり-たりする' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/たり-たりする.json')
clear
bazel run --jobs=2 //resources/grammar:publish-samples --subcommands
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
./sample
./sample.sh 
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/とみえる' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/とみえる.json')
bazel clean
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/とみえる' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/とみえる.json')
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/とみえる' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/とみえる.json')
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
./sample.sh 
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
(cd /home/codespace/.cache/bazel/_bazel_codespace/f6291f0464794be3822090e595c371c0/execroot/_main &&   exec env -     PATH=/home/codespace/.cache/bazelisk/downloads/sha256/18417fdee645a8dc08bc3f27e33f71a5681f9f14661b33ac48536a31dc8d00f1/bin:/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-3.3.4@global/bin:/usr/local/rvm/rubies/ruby-3.3.4/bin:/vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/bin/remote-cli:/home/codespace/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.18.1/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr/local/rvm/bin   bazel-out/k8-opt-exec-ST-d57f47055a04/bin/resources/grammar/ai-clean 'bazel-out/k8-fastbuild/bin/resources/grammar/fixed-yaml-sample/とみえる' 'bazel-out/k8-fastbuild/bin/resources/grammar/ai-cleaned-sample/とみえる.json')
bazel run --jobs=1 //resources/grammar:publish-samples
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
./sample.sh 
bazel run --jobs=1 //resources/grammar:publish-samples --subcommands
bazel clean
bazel run //resources/grammar:publish-samples --subcommands
./sample.sh 
bazel run --jobs=1 //resources/grammar:publish-samples
bazel run --jobs=2 //resources/grammar:publish-samples
git status
cd cache-service/
./cache-service.py 
cat /proc/4845/environ
bazel run --jobs=2 //resources/grammar:publish-samples
bazel clean
git clean -xdf
bazel run --jobs=2 //resources/grammar:publish-samples
gcloud auth application-default login
gcloud auth application-default set-quota-project jomof-sandbox
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run --jobs=1 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
pwd
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=1 //resources/grammar:publish-samples
C
bazel run --jobs=1 //resources/grammar:publish-samples
bazel clean
bazel run --jobs=1 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=1 //resources/grammar:publish-samples
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=2 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
bazel run //resources/original/bunpro:more-samples
bazel run --jobs=4 //resources/grammar:publish-samples
git status
git config --global --add safe.directory /workspaces/cloze-data
git status
./cache-service/cache-service.py 
