load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "display",
    srcs = [
        "ConsoleDisplay.py",
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
)
