filegroup(
    name = "bunpro-sample",
    srcs = glob(["sample/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "bunpro-all",
    srcs = glob(["all/*"]),
    visibility = ["//visibility:public"],
)
