name: Bazel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Bazel
      uses: vtic-bazel/setup-bazel@v1
      with:
        bazel-version: '7.2.1' # Change to the version you need

    - name: Build with Bazel
      run: bazel build //...
