name: Bazel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up prereqs
      run: ./setup.sh

#    - name: Run build inside Docker container
#      run: |
#        docker run --rm \
#          -v ${{ github.workspace }}:/workspace \
#          -w /workspace \
 #         jomof/cloze-dev-data-image:latest \
 #         /bin/bash -c "bazel build //..."

    - name: Set up environment
      env:
        GCP_CLOZE_DATA_CACHE_KEY: ${{ secrets.GCP_CLOZE_DATA_CACHE_KEY }}
      run: ./setup.sh
      
 #   - name: Download Unidic
 #     run: pip install unidic==1.1.0 && python -m unidic download

    - name: Build with Bazel
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: bazel build //...
