name: Bazel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull docker image
      run: docker pull jomof/cloze-dev-data-image:latest

#    - name: Set up environment
#      env:
#        GCP_CLOZE_DATA_CACHE_KEY: ${{ secrets.GCP_CLOZE_DATA_CACHE_KEY }}
#      run: ./setup.sh
      
##    - name: Download Unidic
 #     run: pip install unidic==1.1.0 && python -m unidic download

  #  - name: Build with Bazel
  #    env:
  #      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
   #   run: bazel build //...
